In [1]:
import numpy as np


In [2]:
array = np.array([1,2,3])
print(array)

[1 2 3]


In [3]:
array.shape

(3,)

In [4]:
array2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
array2.reshape(3,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [5]:
array2.ndim

1

In [6]:
array.dtype.name



'int32'

In [7]:
 array2.ndim
    

1

In [8]:
array2.size

15

In [9]:
type(array2)

numpy.ndarray

In [12]:
array3 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [13]:
array3.shape

(3, 4)

In [15]:
zeros = np.zeros((3,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [19]:
a=np.linspace(0,10,20)
a

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
a = np.array([1,2,3])
b=np.array([3,4,5])
print(a-b)

[-2 -2 -2]


In [21]:
print(a*b)

[ 3  8 15]


In [22]:
print(b/a)

[3.         2.         1.66666667]


In [25]:
liste = ([1,2,3,4])
array = np.array([5,6,7,8])
print(liste)
print(array)

[1, 2, 3, 4]
[5 6 7 8]


In [26]:
array=np.array(liste)
array


array([1, 2, 3, 4])

In [27]:
b=a
c=a
b[0]=5
print(a,b,c)

[5 2 3] [5 2 3] [5 2 3]


In [28]:
a[0]=5

In [29]:
d

NameError: name 'd' is not defined

In [30]:
d=a.copy()
d

array([5, 2, 3])

In [31]:
a[0]=5

In [32]:
d

array([5, 2, 3])

In [33]:
print(a[0])

5


In [34]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [35]:
print(b[1,1])

7


In [36]:
b[:,-1]

array([ 5, 10])